In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("./House Price Prediction Dataset.csv")
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,Downtown,Excellent,No,149919
1,2,4272,5,4,3,1958,Downtown,Excellent,No,424998
2,3,3592,2,2,3,1938,Downtown,Good,No,266746
3,4,966,4,2,2,1902,Suburban,Fair,Yes,244020
4,5,4926,1,4,2,1975,Downtown,Fair,Yes,636056

In [3]:
df.isnull().sum()

Id           0
Area         0
Bedrooms     0
Bathrooms    0
Floors       0
YearBuilt    0
Location     0
Condition    0
Garage       0
Price        0
dtype: int64

In [8]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 2000 entries, 0 to 1999
Data columns (total 10 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Id         2000 non-null   int64
 1   Area       2000 non-null   int64
 2   Bedrooms   2000 non-null   int64
 3   Bathrooms  2000 non-null   int64
 4   Floors     2000 non-null   int64
 5   YearBuilt  2000 non-null   int64
 6   Location   2000 non-null   int64
 7   Condition  2000 non-null   int64
 8   Garage     2000 non-null   int64
 9   Price      2000 non-null   int64
dtypes: int64(10)
memory usage: 156.4 KB

In [5]:
df["Location"].unique()
df["Condition"].unique()
df["Garage"].unique()

<StringArray>
['No', 'Yes']
Length: 2, dtype: str

In [6]:
df["Location"] = df["Location"].map(
    {
        "Downtown": 0,
        "Suburban": 1,
        "Urban": 2,
        "Rural": 3,
    }
)

df["Condition"] = df["Condition"].map(
    {
        "Poor": 0,
        "Fair": 1,
        "Good": 2,
        "Excellent": 3,
    }
)

df["Garage"] = df["Garage"].map(
    {
        "No": 0,
        "Yes": 1,
    }
)

In [7]:
df.head()

,Id,Area,Bedrooms,Bathrooms,Floors,YearBuilt,Location,Condition,Garage,Price
0,1,1360,5,4,3,1970,0,3,0,149919
1,2,4272,5,4,3,1958,0,3,0,424998
2,3,3592,2,2,3,1938,0,2,0,266746
3,4,966,4,2,2,1902,1,1,1,244020
4,5,4926,1,4,2,1975,0,1,1,636056

In [9]:
X = df.drop("Price", axis=1)
y = df["Price"]