In [2]:
import pandas as pd

train = pd.read_csv("../model_training/train.csv")

In [3]:
train.info()

<class 'pandas.DataFrame'>
RangeIndex: 29451 entries, 0 to 29450
Data columns (total 12 columns):
 #   Column                 Non-Null Count  Dtype
---  ------                 --------------  -----
 0   POSTED_BY              29451 non-null  str
 1   UNDER_CONSTRUCTION     29451 non-null  int64
 2   RERA                   29451 non-null  int64
 3   BHK_NO.                29451 non-null  int64
 4   BHK_OR_RK              29451 non-null  str
 5   SQUARE_FT              29451 non-null  float64
 6   READY_TO_MOVE          29451 non-null  int64
 7   RESALE                 29451 non-null  int64
 8   ADDRESS                29451 non-null  str
 9   LONGITUDE              29451 non-null  float64
 10  LATITUDE               29451 non-null  float64
 11  TARGET(PRICE_IN_LACS)  29451 non-null  float64
dtypes: float64(4), int64(5), str(3)
memory usage: 2.7 MB

In [4]:
train.head()

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,ADDRESS,LONGITUDE,LATITUDE,TARGET(PRICE_IN_LACS)
0,Owner,0,0,2,BHK,1300.236407,1,1,"Ksfc Layout,Bangalore",12.969910,77.597960,55.0
1,Dealer,0,0,2,BHK,1275.000000,1,1,"Vishweshwara Nagar,Mysore",12.274538,76.644605,51.0
2,Owner,0,0,2,BHK,933.159722,1,1,"Jigani,Bangalore",12.778033,77.632191,43.0
3,Owner,0,1,2,BHK,929.921143,1,1,"Sector-1 Vaishali,Ghaziabad",28.642300,77.344500,62.5
4,Dealer,1,0,2,BHK,999.009247,0,1,"New Town,Kolkata",22.592200,88.484911,60.5

In [5]:
train.nunique()

POSTED_BY                    3
UNDER_CONSTRUCTION           2
RERA                         2
BHK_NO.                     16
BHK_OR_RK                    2
SQUARE_FT                19561
READY_TO_MOVE                2
RESALE                       2
ADDRESS                   6899
LONGITUDE                 4087
LATITUDE                  4078
TARGET(PRICE_IN_LACS)     1172
dtype: int64

In [6]:
train["POSTED_BY"] = train["POSTED_BY"].map({'Owner': 0, 'Dealer': 1, 'Builder': 2})
train["BHK_OR_RK"] = train["BHK_OR_RK"].map({"BHK": 0, "RK": 1})
train = train.drop(columns=["ADDRESS", "LONGITUDE", "LATITUDE"])

In [7]:
train.corr(method="spearman")

,POSTED_BY,UNDER_CONSTRUCTION,RERA,BHK_NO.,BHK_OR_RK,SQUARE_FT,READY_TO_MOVE,RESALE,TARGET(PRICE_IN_LACS)
POSTED_BY,1.000000,0.253763,0.283767,0.094068,0.025143,0.099778,-0.253763,-0.290961,0.345664
UNDER_CONSTRUCTION,0.253763,1.000000,0.363826,-0.039270,0.020719,-0.106973,-1.000000,-0.347405,0.042613
RERA,0.283767,0.363826,1.000000,0.022769,0.006056,0.011442,-0.363826,-0.270351,0.150868
BHK_NO.,0.094068,-0.039270,0.022769,1.000000,-0.046880,0.817604,0.039270,0.012727,0.500700
BHK_OR_RK,0.025143,0.020719,0.006056,-0.046880,1.000000,-0.048546,-0.020719,-0.029346,-0.021108
SQUARE_FT,0.099778,-0.106973,0.011442,0.817604,-0.048546,1.000000,0.106973,0.084046,0.570263
READY_TO_MOVE,-0.253763,-1.000000,-0.363826,0.039270,-0.020719,0.106973,1.000000,0.347405,-0.042613
RESALE,-0.290961,-0.347405,-0.270351,0.012727,-0.029346,0.084046,0.347405,1.000000,-0.036893
TARGET(PRICE_IN_LACS),0.345664,0.042613,0.150868,0.500700,-0.021108,0.570263,-0.042613,-0.036893,1.000000

In [8]:
X = train[["POSTED_BY", "BHK_NO.", "SQUARE_FT", "RERA", "TARGET(PRICE_IN_LACS)"]]

In [9]:
X.head()

   POSTED_BY  BHK_NO.    SQUARE_FT  RERA  TARGET(PRICE_IN_LACS)
0          0        2  1300.236407     0                   55.0
1          1        2  1275.000000     0                   51.0
2          0        2   933.159722     0                   43.0
3          0        2   929.921143     1                   62.5
4          1        2   999.009247     0                   60.5

In [10]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)
X_scaled

array([[-1.28713168, -0.44623962, -0.00973119, -0.68271456, -0.13381461],
       [ 0.65335028, -0.44623962, -0.00974446, -0.68271456, -0.1399041 ],
       [-1.28713168, -0.44623962, -0.00992425, -0.68271456, -0.15208308],
       ...,
       [ 0.65335028, -0.44623962, -0.00987719, -0.68271456, -0.1762888 ],
       [-1.28713168, -0.44623962, -0.00992745, -0.68271456, -0.11554615],
       [ 0.65335028, -0.44623962, -0.00994339,  1.464741  , -0.17522314]],
      shape=(29451, 5))

In [11]:
X = pd.DataFrame(X_scaled, columns=X.columns)

In [12]:
X

       POSTED_BY   BHK_NO.  SQUARE_FT      RERA  TARGET(PRICE_IN_LACS)
0      -1.287132 -0.446240  -0.009731 -0.682715              -0.133815
1       0.653350 -0.446240  -0.009744 -0.682715              -0.139904
2      -1.287132 -0.446240  -0.009924 -0.682715              -0.152083
3      -1.287132 -0.446240  -0.009926  1.464741              -0.122397
4       0.653350 -0.446240  -0.009890 -0.682715              -0.125442
...          ...       ...        ...       ...                    ...
29446  -1.287132  0.691318  -0.009100 -0.682715              -0.149038
29447  -1.287132 -0.446240  -0.010010 -0.682715              -0.193187
29448   0.653350 -0.446240  -0.009877 -0.682715              -0.176289
29449  -1.287132 -0.446240  -0.009927 -0.682715              -0.115546
29450   0.653350 -0.446240  -0.009943  1.464741              -0.175223

[29451 rows x 5 columns]

In [13]:
y = X["TARGET(PRICE_IN_LACS)"]
X = X.drop(columns="TARGET(PRICE_IN_LACS)")

In [14]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [31]:
from sklearn.ensemble import RandomForestRegressor
forest = RandomForestRegressor(n_estimators=1000, max_depth=10)
forest.fit(X_train, y_train)
forest.score(X_train, y_train)

0.9605244663756597

In [32]:
from sklearn.metrics import r2_score, mean_absolute_error
import numpy as np
prediction = forest.predict(X_test)
print(r2_score(y_test, prediction))
print(np.sqrt(mean_absolute_error(y_test, prediction)))

0.700820145924378
0.31347479556000335

In [ ]:
from sklearn.model_selection import cross_val_score

scores = cross_val_score(forest, X, y, cv=5, scoring="r2")
print("CV R2:", scores.mean())

CV R2: 0.843546863441708

In [34]:
print(scores)

[0.90264827 0.88486722 0.7140525  0.8680435  0.84812283]